#include <wx/aui/aui.h>
#include <wx/wx.h>
#include <wx/sizer.h>
#include <wx/notebook.h>
#include <wx/listctrl.h>
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>
#include <numeric>
#include <functional>